import {
  Award,
  Bell,
  Briefcase,
  Calendar,
  CircleDollarSign,
  ClipboardCheck,
  Clock,
  Factory,
  Bot,
  FilePen,
  FileStack,
  FileText,
  Globe,
  Handshake,
  KeyRound,
  LayoutDashboard,
  List,
  Megaphone,
  MessageSquare,
  Package,
  Radar,
  Scan,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  SlidersHorizontal,
  Store,
  Tags,
  Target,
  Truck,
  User,
  UserPlus,
  Users,
  type LucideIcon,
} from 'lucide-react';

export const DASHBOARD_NAV_ICONS = {
  layoutDashboard: LayoutDashboard,
  list: List,
  users: Users,
  user: User,
  shieldCheck: ShieldCheck,
  award: Award,
  messageSquare: MessageSquare,
  handshake: Handshake,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  briefcase: Briefcase,
  factory: Factory,
  bot: Bot,
  calendar: Calendar,
  fileText: FileText,
  megaphone: Megaphone,
  globe: Globe,
  bell: Bell,
  settings: Settings,
  keyRound: KeyRound,
  userPlus: UserPlus,
  fileStack: FileStack,
  filePen: FilePen,
  tags: Tags,
  scan: Scan,
  truck: Truck,
  package: Package,
  ship: Ship,
  store: Store,
  radar: Radar,
  shield: Shield,
  circleDollarSign: CircleDollarSign,
  target: Target,
  slidersHorizontal: SlidersHorizontal,
} as const satisfies Record<string, LucideIcon>;

export type DashboardNavIconKey = keyof typeof DASHBOARD_NAV_ICONS;

export function getDashboardNavIcon(iconKey: DashboardNavIconKey | undefined): LucideIcon | null {
  if (!iconKey) {
    return null;
  }
  return DASHBOARD_NAV_ICONS[iconKey] ?? null;
}
