import { ORG_ADMIN_ROLE_KEY, SUPER_ADMIN_ROLE_KEY, USER_ROLE_KEY } from '@/lib/roles';

export const SUPER_ADMIN_ALLOWED_ROLES = [SUPER_ADMIN_ROLE_KEY] as const;
export const ORG_DASHBOARD_ALLOWED_ROLES = [ORG_ADMIN_ROLE_KEY, USER_ROLE_KEY] as const;
