/** Stable API (non-auth) error codes — frontend maps `errors.${code}` via next-intl (see translateAuthCode). */
export const API_ERROR_CODES = {
  // Shared reasons (api.common.*) — reused across domains.
  COMMON_NO_FIELDS_TO_UPDATE: 'api.common.no_fields_to_update',
  COMMON_NAME_REQUIRED: 'api.common.name_required',
  COMMON_WRONG_ACTIVE_ROLE: 'api.common.wrong_active_role',

  // Manufacturers (pilot domain — A.6). Other catalog/profile/onboarding domains
  // append their codes in their own migration tickets (additive).
  MANUFACTURER_KEY_EXISTS: 'api.manufacturer.key_exists',
  MANUFACTURER_KEY_PREVIOUSLY_DELETED: 'api.manufacturer.key_previously_deleted',
  MANUFACTURER_NOT_FOUND: 'api.manufacturer.not_found',

  INSPECTION_LISTING_NOT_FOUND: 'api.inspection.listing_not_found',
  INSPECTION_LISTING_NOT_ELIGIBLE: 'api.inspection.listing_not_eligible',
  INSPECTION_REQUEST_ALREADY_EXISTS: 'api.inspection.request_already_exists',
  INSPECTION_CANNOT_REQUEST_OWN_LISTING: 'api.inspection.cannot_request_own_listing',

  NOTIFICATION_NOT_FOUND: 'api.notification.not_found',

  USER_NOT_FOUND: 'api.user.not_found',
  USER_DELETED_CANNOT_UPDATE: 'api.user.deleted_cannot_update',
  USER_CANNOT_DEACTIVATE_SELF: 'api.user.cannot_deactivate_self',
  USER_LAST_ACTIVE_ADMIN: 'api.user.last_active_admin',
  USER_ACCOUNT_DEACTIVATED: 'api.user.account_deactivated',

  ONBOARDING_JOIN_NOT_ELIGIBLE: 'api.onboarding.join_not_eligible',
  ONBOARDING_BUYER_USE_UPGRADE: 'api.onboarding.buyer_use_upgrade',
  ONBOARDING_APPLICATION_PENDING: 'api.onboarding.application_pending',
  ONBOARDING_APPLICATION_ALREADY_PENDING: 'api.onboarding.application_already_pending',
  ONBOARDING_APPROVE_USER_EXISTS: 'api.onboarding.approve_user_exists',
  ONBOARDING_UPGRADE_NOT_ELIGIBLE: 'api.onboarding.upgrade_not_eligible',

  USE_CASE_NOT_FOUND: 'api.use_case.not_found',
  USE_CASE_KEY_EXISTS: 'api.use_case.key_exists',
  USE_CASE_KEY_PREVIOUSLY_DELETED: 'api.use_case.key_previously_deleted',
  USE_CASE_INVALID_PARENT: 'api.use_case.invalid_parent',
  USE_CASE_CYCLIC_PARENT: 'api.use_case.cyclic_parent',
  USE_CASE_MAX_DEPTH_EXCEEDED: 'api.use_case.max_depth_exceeded',
  USE_CASE_PARENT_DELETED: 'api.use_case.parent_deleted',

  LISTING_MANUFACTURER_REQUIRED: 'api.listing.manufacturer_required',
  LISTING_MODEL_NOT_FOUND: 'api.listing.model_not_found',
  LISTING_MODEL_MANUFACTURER_MISMATCH: 'api.listing.model_manufacturer_mismatch',
  LISTING_USE_CASE_NOT_FOUND: 'api.listing.use_case_not_found',
  LISTING_USE_CASE_DUPLICATE_OR_EMPTY: 'api.listing.use_case_duplicate_or_empty',
  LISTING_INSUFFICIENT_STOCK: 'api.listing.insufficient_stock',
  LISTING_INVALID_INVENTORY_UNITS: 'api.listing.invalid_inventory_units',
  LISTING_INVENTORY_QUANTITY_EXCEEDED: 'api.listing.inventory_quantity_exceeded',
  LISTING_WRONG_SELLER_SURFACE: 'api.listing.wrong_seller_surface',
  LISTING_WRONG_PARTNER_SURFACE: 'api.listing.wrong_partner_surface',

  LISTING_DRAFT_NOT_FOUND: 'api.listing_draft.not_found',
  LISTING_DRAFT_LIMIT_EXCEEDED: 'api.listing_draft.limit_exceeded',

  CATALOG_BULK_INVALID_CSV: 'api.catalog_bulk.invalid_csv',
  CATALOG_BULK_EMPTY_FILE: 'api.catalog_bulk.empty_file',
  CATALOG_BULK_FILE_SIZE_EXCEEDED: 'api.catalog_bulk.file_size_exceeded',
  CATALOG_BULK_ROW_LIMIT_EXCEEDED: 'api.catalog_bulk.row_limit_exceeded',
  CATALOG_BULK_PREVIEW_UNAVAILABLE: 'api.catalog_bulk.preview_unavailable',
  CATALOG_BULK_PREVIEW_NOT_FOUND: 'api.catalog_bulk.preview_not_found',
  CATALOG_BULK_PREVIEW_STALE: 'api.catalog_bulk.preview_stale',
  CATALOG_BULK_COMMIT_IN_PROGRESS: 'api.catalog_bulk.commit_in_progress',
  CATALOG_BULK_RESTORE_CONFIRMATION_REQUIRED: 'api.catalog_bulk.restore_confirmation_required',
  CATALOG_BULK_SCOPE_NOT_FOUND: 'api.catalog_bulk.scope_not_found',
  CATALOG_BULK_PREVIEW_CONSUME_FAILED: 'api.catalog_bulk.preview_consume_failed',

  PUBLIC_PAGE_NOT_FOUND: 'api.public_page.not_found',
  PUBLIC_PAGE_UNPUBLISHED: 'api.public_page.unpublished',
  PUBLIC_PAGE_KEY_EXISTS: 'api.public_page.key_exists',
  PUBLIC_PAGE_KEY_RESERVED: 'api.public_page.key_reserved',

  PAYMENT_DISABLED: 'api.payment.disabled',
  PAYMENT_PROVIDER_NOT_CONFIGURED: 'api.payment.provider_not_configured',
  PAYMENT_SELLER_NOT_READY: 'api.payment.seller_not_ready',
  PAYMENT_CANNOT_BUY_OWN_LISTING: 'api.payment.cannot_buy_own_listing',
  PAYMENT_WRONG_BUYER_SURFACE: 'api.payment.wrong_buyer_surface',
  PAYMENT_LISTING_NOT_ELIGIBLE: 'api.payment.listing_not_eligible',
  PAYMENT_PRICE_NOT_AVAILABLE: 'api.payment.price_not_available',
  PAYMENT_CURRENCY_NOT_SUPPORTED: 'api.payment.currency_not_supported',
  PAYMENT_TRANSACTION_NOT_FOUND: 'api.payment.transaction_not_found',
  PAYMENT_PAYOUT_NOT_ELIGIBLE: 'api.payment.payout_not_eligible',
  PAYMENT_RELEASE_NOT_ELIGIBLE: 'api.payment.release_not_eligible',
  PAYMENT_ALREADY_RELEASED: 'api.payment.already_released',
  PAYMENT_WEBHOOK_SIGNATURE_INVALID: 'api.payment.webhook_signature_invalid',
  SELLER_TRUST_BADGE_NOT_ELIGIBLE: 'api.seller_trust_badge.not_eligible',
  SELLER_TRUST_BADGE_REQUEST_PENDING: 'api.seller_trust_badge.request_pending',
  SELLER_TRUST_BADGE_ALREADY_HELD: 'api.seller_trust_badge.already_held',
  SELLER_TRUST_BADGE_REQUEST_NOT_FOUND: 'api.seller_trust_badge.request_not_found',
  SELLER_TRUST_BADGE_REQUEST_NOT_PENDING: 'api.seller_trust_badge.request_not_pending',
  SELLER_TRUST_BADGE_BADGE_NOT_FOUND: 'api.seller_trust_badge.badge_not_found',
  SELLER_TRUST_BADGE_BADGE_NOT_ACTIVE: 'api.seller_trust_badge.badge_not_active',

  EXPERT_CREDITS_INSUFFICIENT_BALANCE: 'api.expert_credits.insufficient_balance',
  EXPERT_CREDITS_PACKAGE_NOT_FOUND: 'api.expert_credits.package_not_found',
  EXPERT_CREDITS_PACKAGE_NOT_ACTIVE: 'api.expert_credits.package_not_active',
  EXPERT_CREDITS_PACKAGE_NOT_PRICED: 'api.expert_credits.package_not_priced',
  EXPERT_CREDITS_PURCHASE_NOT_FOUND: 'api.expert_credits.purchase_not_found',
  EXPERT_CREDITS_WALLET_NOT_FOUND: 'api.expert_credits.wallet_not_found',
  EXPERT_CREDITS_ADJUSTMENT_NOTE_REQUIRED: 'api.expert_credits.adjustment_note_required',
  EXPERT_CREDITS_KEY_EXISTS: 'api.expert_credits.key_exists',
  EXPERT_CREDITS_KEY_PREVIOUSLY_DELETED: 'api.expert_credits.key_previously_deleted',
  EXPERT_CREDITS_WORK_CATEGORY_NOT_FOUND: 'api.expert_credits.work_category_not_found',
  EXPERT_CREDITS_RESERVATION_NOT_FOUND: 'api.expert_credits.reservation_not_found',
  EXPERT_CREDITS_RESERVATION_NOT_ACTIVE: 'api.expert_credits.reservation_not_active',
  EXPERT_CREDITS_INVALID_RESERVATION_AMOUNT: 'api.expert_credits.invalid_reservation_amount',
  EXPERT_CREDITS_COMMITTED_AMOUNT_EXCEEDS_RESERVATION: 'api.expert_credits.committed_amount_exceeds_reservation',
  EXPERT_CREDITS_WORK_CATEGORY_INACTIVE: 'api.expert_credits.work_category_inactive',
  EXPERT_CREDITS_PURCHASE_NOT_REFUNDABLE: 'api.expert_credits.purchase_not_refundable',

  MATCH_SESSION_NOT_FOUND: 'api.matching.session_not_found',
  MATCH_SESSION_DEVICE_MISMATCH: 'api.matching.session_device_mismatch',
  MATCH_SESSION_NOT_RUN: 'api.matching.session_not_run',
  MATCH_SESSION_ALREADY_CLAIMED: 'api.matching.session_already_claimed',
  MATCH_RESULT_NOT_FOUND: 'api.matching.result_not_found',
  MATCH_WEIGHTS_INVALID_TOTAL: 'api.matching.weights_invalid_total',
  MATCH_THRESHOLDS_INVALID: 'api.matching.thresholds_invalid',
  MATCH_SAVE_REQUIRES_AUTH: 'api.matching.save_requires_auth',
  MATCH_ALREADY_SAVED: 'api.matching.already_saved',
  MATCH_SAVED_NOT_FOUND: 'api.matching.saved_not_found',
  MATCH_OVERRIDE_REQUIRES_REASON: 'api.matching.override_requires_reason',
  MATCH_DEVICE_ID_REQUIRED: 'api.matching.device_id_required',
  MATCH_WRONG_BUYER_SURFACE: 'api.matching.wrong_buyer_surface',
  MATCH_TOO_MANY_RUNS: 'api.matching.too_many_runs',
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
