/**
 * Stable `data-testid` registry — the single source of truth for test ids.
 *
 * The frontend sets these on elements (via the `testId` prop on shared
 * primitives, or `data-testid` directly); the e2e suite (`@constellation/e2e`)
 * locates by them. Keeping both sides on one typed object means no typos and
 * safe renames.
 *
 * Conventions:
 * - `<feature>-<element>[-<qualifier>]`, kebab-case.
 * - List/row ids embed a stable entity key — never an array index.
 * - Never derive an id from translated (i18n) text.
 *
 * Grow this per feature as test ids are added (see the test-id coverage plan).
 */
export const TEST_IDS = {
  /** Default id for a Formik field, derived from its `name` (e.g. `field-email`). */
  field: (name: string) => `field-${name}`,
  signIn: {
    email: 'signin-email',
    password: 'signin-password',
    submit: 'signin-submit',
  },
  signUp: {
    name: 'signup-name',
    email: 'signup-email',
    password: 'signup-password',
    confirmPassword: 'signup-confirm-password',
    submit: 'signup-submit',
  },
  forgotPassword: {
    email: 'forgot-email',
    submit: 'forgot-submit',
  },
  resetPassword: {
    password: 'reset-password',
    confirmPassword: 'reset-confirm-password',
    submit: 'reset-submit',
  },
  auth: {
    error: 'auth-error',
    verificationPending: 'auth-verification-pending',
    google: 'auth-google',
    resendVerification: 'auth-resend-verification',
  },
  onboardingOrg: {
    name: 'onboarding-org-name',
    address: 'onboarding-org-address',
    submit: 'onboarding-org-submit',
  },
  nav: {
    dashboard: 'nav-dashboard',
    signIn: 'nav-sign-in',
    signUp: 'nav-sign-up',
    joinTeam: 'nav-join-team',
    signOut: 'nav-sign-out',
    profile: 'nav-profile',
    accountMenu: 'nav-account-menu',
    manufacturers: 'nav-manufacturers',
    themeToggle: 'theme-toggle',
    localeSwitcher: 'locale-switcher',
    brand: 'nav-brand',
  },
  dashboardNav: {
    mobileOpen: 'dashboard-nav-open',
    mobileClose: 'dashboard-nav-close',
    /** Collapsible group header by stable group key. */
    group: (key: string) => `dashboard-nav-group-${key}`,
    /** Nav link by route href. */
    item: (href: string) => `dashboard-nav-item-${href}`,
    signOut: 'dashboard-nav-sign-out',
  },
  dashboard: {
    roleSwitcher: 'dashboard-role-switcher',
  },
  buyerUpgrade: {
    sellerCta: 'buyer-upgrade-seller-cta',
    switchToSellerCta: 'buyer-upgrade-switch-to-seller-cta',
    backToBuyer: 'buyer-upgrade-back-to-buyer',
    next: 'buyer-upgrade-next',
  },
  changePassword: {
    dialog: 'change-password-dialog',
    cancel: 'change-password-cancel',
    submit: 'change-password-submit',
  },
  profileSettings: {
    submit: 'profile-settings-submit',
    changePassword: 'profile-change-password',
    manageSessions: 'profile-manage-sessions',
    sellerUpgrade: 'profile-seller-upgrade',
  },
  /**
   * Generic catalog admin form (create/edit dialogs). One dialog is open at a
   * time, so the same ids are reused across every catalog type. Fields are
   * covered automatically by the Formik field components (`field-<name>`).
   */
  catalogForm: {
    cancel: 'catalog-form-cancel',
    submit: 'catalog-form-submit',
  },
  join: {
    stepIndicator: 'join-step-indicator',
    next: 'join-next',
    back: 'join-back',
    backHome: 'join-back-home',
    changeGoogleAccount: 'join-change-google-account',
    useEmailPassword: 'join-use-email-password',
    accountType: (key: string) => `join-account-type-${key}`,
    role: (key: string) => `join-role-${key}`,
    document: (id: string) => `join-document-${id}`,
  },
  /** Admin catalog list views (add button + per-row edit/delete by entity key). */
  catalog: {
    add: 'catalog-add',
    edit: (key: string) => `catalog-edit-${key}`,
    delete: (key: string) => `catalog-delete-${key}`,
    row: (key: string) => `catalog-row-${key}`,
    addChild: (key: string) => `use-case-add-child-${key}`,
    expand: (key: string) => `use-case-expand-${key}`,
    bulkDownload: 'catalog-bulk-download',
    bulkDownloadSample: 'catalog-bulk-download-sample',
    bulkUpload: 'catalog-bulk-upload',
    bulkImportDialog: 'catalog-bulk-import-dialog',
    bulkImportPage: 'catalog-bulk-import-page',
    bulkBack: 'catalog-bulk-back',
    bulkSelectFile: 'catalog-bulk-select-file',
    bulkFileInput: 'catalog-bulk-file',
    bulkConfirm: 'catalog-bulk-confirm',
    bulkClose: 'catalog-bulk-close',
    bulkCancel: 'catalog-bulk-cancel',
    bulkReupload: 'catalog-bulk-reupload',
    bulkRestoreAck: 'catalog-bulk-restore-ack',
    bulkTabs: 'catalog-bulk-tabs',
    bulkFileErrors: 'catalog-bulk-file-errors',
    bulkPreviewTable: 'catalog-bulk-preview-table',
    bulkPreviewRow: (line: number) => `catalog-bulk-preview-row-${line}`,
    bulkSummaryCards: 'catalog-bulk-summary-cards',
    bulkSummaryCreated: 'catalog-bulk-summary-created',
    bulkSummaryUpdated: 'catalog-bulk-summary-updated',
    bulkSummarySkipped: 'catalog-bulk-summary-skipped',
    bulkSummaryRestored: 'catalog-bulk-summary-restored',
    bulkSummaryFailed: 'catalog-bulk-summary-failed',
    bulkTab: (section: string) => `catalog-bulk-tab-${section}`,
  },
  /** Shared confirm/cancel actions on catalog delete and restore dialogs. */
  catalogDialog: {
    deleteCancel: 'catalog-delete-cancel',
    deleteConfirm: 'catalog-delete-confirm',
    restoreCancel: 'catalog-restore-cancel',
    restoreConfirm: 'catalog-restore-confirm',
  },
  roles: {
    row: (key: string) => `role-row-${key}`,
  },
  users: {
    view: (id: string) => `user-view-${id}`,
    back: 'user-detail-back',
    detailPanel: 'user-detail-panel',
    panelRefresh: 'user-detail-panel-refresh',
    openFullPage: 'user-detail-open-full-page',
    search: 'users-list-search',
    refresh: 'users-list-refresh',
    accountTypeFilter: 'users-account-type-filter',
    roleFilter: 'users-role-filter',
    retry: 'users-list-retry',
    detailRetry: 'user-detail-retry',
    deactivateCancel: 'user-deactivate-cancel',
    deactivateConfirm: 'user-deactivate-confirm',
    statusTabs: 'users-status-tabs',
  },
  countries: {
    panel: 'country-detail-panel',
    table: 'countries-table',
    listLoading: 'countries-list-loading',
    listRetry: 'countries-list-retry',
    createDialog: 'country-create-dialog',
    createForm: 'country-create-form',
    deleteDialog: 'country-delete-dialog',
    restoreDialog: 'country-restore-dialog',
    detailsSection: 'country-details-section',
    detailsForm: 'country-details-form',
    detailsReadOnly: 'country-details-readonly',
    keyDisplay: 'country-key-display',
    save: 'country-details-save',
    retry: 'country-panel-retry',
    loading: 'country-panel-loading',
    citiesSection: 'country-cities-section',
    citiesTable: 'country-cities-table',
    addCity: 'country-add-city',
    citiesRetry: 'country-cities-retry',
    citiesLoading: 'country-cities-loading',
  },
  cities: {
    formDialog: 'city-form-dialog',
    deleteDialog: 'city-delete-dialog',
    restoreDialog: 'city-restore-dialog',
    form: 'city-form',
    keyDisplay: 'city-key-display',
    edit: (key: string) => `city-edit-${key}`,
    delete: (key: string) => `city-delete-${key}`,
    row: (key: string) => `city-row-${key}`,
  },
  teamApplications: {
    view: (id: string) => `application-view-${id}`,
    rejectReason: 'reject-reason',
    sourceFilter: 'team-applications-source-filter',
    search: 'team-applications-list-search',
    refresh: 'team-applications-list-refresh',
  },
  adminListings: {
    view: (id: string) => `admin-listing-view-${id}`,
    search: 'admin-listings-list-search',
    refresh: 'admin-listings-list-refresh',
    panelRefresh: 'admin-listing-panel-refresh',
    detailRefresh: 'admin-listing-detail-refresh',
  },
  adminStaleReview: {
    view: (id: string) => `admin-stale-review-view-${id}`,
    search: 'admin-stale-review-list-search',
    refresh: 'admin-stale-review-list-refresh',
  },
  adminInspections: {
    statusFilter: 'admin-inspections-status-filter',
    scenarioFilter: 'admin-inspections-scenario-filter',
    search: 'admin-inspections-list-search',
    refresh: 'admin-inspections-list-refresh',
    view: (id: string) => `admin-inspection-view-${id}`,
    openDealRoomTable: (id: string) => `admin-inspections-table-deal-room-${id}`,
    back: 'admin-inspection-back',
    openDealRoom: 'admin-inspection-open-deal-room',
    retry: 'admin-inspections-retry',
    panelRefresh: 'admin-inspection-panel-refresh',
    detailRefresh: 'admin-inspection-detail-refresh',
    assignTrigger: 'admin-inspection-assign-trigger',
    assignSelect: 'admin-inspection-assign-select',
    assignConfirm: 'admin-inspection-assign-confirm',
    assignCancel: 'admin-inspection-assign-cancel',
    reviewTrigger: 'admin-inspection-review-trigger',
    decisionTrigger: 'admin-inspection-decision-trigger',
    decisionOutcome: 'admin-inspection-decision-outcome',
    decisionNotes: 'admin-inspection-decision-notes',
    decisionConfirm: 'admin-inspection-decision-confirm',
    decisionCancel: 'admin-inspection-decision-cancel',
    badgeGrant: (badge: string) => `admin-inspection-badge-grant-${badge}`,
    badgeRevoke: (badge: string) => `admin-inspection-badge-revoke-${badge}`,
    reportDoc: (fileName: string) => `admin-inspection-report-doc-${fileName}`,
  },
  partnerInspections: {
    statusFilter: 'partner-inspections-status-filter',
    panelRefresh: 'partner-inspection-panel-refresh',
    detailRefresh: 'partner-inspection-detail-refresh',
    view: (id: string) => `partner-inspection-view-${id}`,
    openDealRoomTable: (id: string) => `partner-inspections-table-deal-room-${id}`,
    back: 'partner-inspection-back',
    openDealRoom: 'partner-inspection-open-deal-room',
    retry: 'partner-inspections-retry',
    scheduleTrigger: 'partner-inspection-schedule-trigger',
    scheduleDate: 'partner-inspection-schedule-date',
    scheduleConfirm: 'partner-inspection-schedule-confirm',
    scheduleCancel: 'partner-inspection-schedule-cancel',
    startTrigger: 'partner-inspection-start-trigger',
    reportTrigger: 'partner-inspection-report-trigger',
    reportBody: 'partner-inspection-report-body',
    reportFile: 'partner-inspection-report-file',
    reportRemoveDoc: (key: string) => `partner-inspection-report-remove-${key}`,
    reportSubmit: 'partner-inspection-report-submit',
    reportCancel: 'partner-inspection-report-cancel',
    reportDoc: (fileName: string) => `partner-inspection-report-doc-${fileName}`,
  },
  buyerInspections: {
    statusFilter: 'buyer-inspections-status-filter',
    refresh: 'buyer-inspections-list-refresh',
    panelRefresh: 'buyer-inspections-panel-refresh',
    detailRefresh: 'buyer-inspections-detail-refresh',
    openDealRoom: (id: string) => `buyer-inspections-open-deal-room-${id}`,
    view: (id: string) => `buyer-inspections-view-${id}`,
    back: 'buyer-inspections-back',
    reportDoc: (fileName: string) => `buyer-inspections-report-doc-${fileName}`,
    retry: 'buyer-inspections-retry',
    reviewTrigger: (id: string) => `buyer-inspections-review-${id}`,
    decisionProceed: 'buyer-inspections-decision-proceed',
    decisionRenegotiate: 'buyer-inspections-decision-renegotiate',
    decisionCancel: 'buyer-inspections-decision-cancel',
    decisionConfirm: 'buyer-inspections-decision-confirm',
    decisionDismiss: 'buyer-inspections-decision-dismiss',
  },
  sellerInspections: {
    statusFilter: 'seller-inspections-status-filter',
    refresh: 'seller-inspections-list-refresh',
    panelRefresh: 'seller-inspections-panel-refresh',
    detailRefresh: 'seller-inspections-detail-refresh',
    openDealRoom: (id: string) => `seller-inspections-open-deal-room-${id}`,
    view: (id: string) => `seller-inspections-view-${id}`,
    back: 'seller-inspections-back',
    reportDoc: (fileName: string) => `seller-inspections-report-doc-${fileName}`,
    retry: 'seller-inspections-retry',
  },
  verification: {
    listRefresh: 'verification-refresh',
    retry: 'verification-retry',
    card: (badgeType: string, domain: string) => `verification-card-${badgeType}-${domain}`,
    apply: (badgeType: string, domain: string) => `verification-apply-${badgeType}-${domain}`,
    applyDialog: 'verification-apply-dialog',
    applyNote: 'verification-apply-note',
    applyField: (name: string) => `verification-apply-field-${name}`,
    applyFile: 'verification-apply-file',
    applyAddFiles: 'verification-apply-add-files',
    applyRemoveDoc: (key: string) => `verification-apply-remove-${key}`,
    applyCancel: 'verification-apply-cancel',
    applySubmit: 'verification-apply-submit',
    viewModerationMessage: (badgeType: string, domain: string) =>
      `verification-view-moderation-${badgeType}-${domain}`,
    viewModerationDialog: 'verification-view-moderation-dialog',
  },
  adminTrustBadges: {
    listRefresh: 'admin-trust-badges-refresh',
    search: 'admin-trust-badges-search',
    statusTabs: 'admin-trust-badges-status-tabs',
    statusFilter: 'admin-trust-badges-status-filter',
    badgeTypeFilter: 'admin-trust-badges-badge-type-filter',
    domainFilter: 'admin-trust-badges-domain-filter',
    pagination: 'admin-trust-badges-pagination',
    table: 'admin-trust-badges-table',
    row: (id: string) => `admin-trust-badges-row-${id}`,
    view: (id: string) => `admin-trust-badges-view-${id}`,
    detailRefresh: 'admin-trust-badge-detail-refresh',
    approve: 'admin-trust-badge-approve',
    reject: 'admin-trust-badge-reject',
    revoke: 'admin-trust-badge-revoke',
    decisionDialog: 'admin-trust-badge-decision-dialog',
    decisionMessage: 'admin-trust-badge-decision-message',
    decisionSubmit: 'admin-trust-badge-decision-submit',
    decisionCancel: 'admin-trust-badge-decision-cancel',
    downloadDoc: (id: string) => `admin-trust-badge-doc-${id}`,
    viewNote: 'admin-trust-badge-view-note',
    viewDecision: 'admin-trust-badge-view-decision',
  },
  sellerListings: {
    panelRefresh: 'seller-listing-panel-refresh',
    detailRefresh: 'seller-listing-detail-refresh',
    listRefresh: 'seller-listings-refresh',
    confirmAvailable: 'seller-listing-confirm-available',
    view: (id: string) => `seller-listing-view-${id}`,
  },
  sellerListingDrafts: {
    saveDraft: 'seller-listing-draft-save-exit',
    viewDrafts: 'seller-listing-drafts-view',
    startListing: 'seller-listing-drafts-start',
    retry: 'seller-listing-drafts-retry',
    listRefresh: 'seller-listing-drafts-refresh',
    back: 'seller-listing-drafts-back',
    stepIndicator: 'seller-listing-draft-step-indicator',
    resume: (id: string) => `seller-listing-draft-resume-${id}`,
    delete: (id: string) => `seller-listing-draft-delete-${id}`,
    deleteDialog: 'seller-listing-draft-delete-dialog',
    confirmDelete: 'seller-listing-draft-confirm-delete',
    cancelDelete: 'seller-listing-draft-cancel-delete',
  },
  partnerListingDrafts: {
    saveDraft: 'partner-listing-draft-save-exit',
    viewDrafts: 'partner-listing-drafts-view',
    startListing: 'partner-listing-drafts-start',
    retry: 'partner-listing-drafts-retry',
    listRefresh: 'partner-listing-drafts-refresh',
    back: 'partner-listing-drafts-back',
    stepIndicator: 'partner-listing-draft-step-indicator',
    resume: (id: string) => `partner-listing-draft-resume-${id}`,
    delete: (id: string) => `partner-listing-draft-delete-${id}`,
    deleteDialog: 'partner-listing-draft-delete-dialog',
    confirmDelete: 'partner-listing-draft-confirm-delete',
    cancelDelete: 'partner-listing-draft-cancel-delete',
  },
  certifiedStock: {
    // Per-listing "Request Certified inspection" action on the dealer's listing detail (Epic 8)
    requestListingTrigger: 'certified-stock-request-listing-trigger',
    requestListingConfirm: 'certified-stock-request-listing-confirm',
    requestListingCancel: 'certified-stock-request-listing-cancel',
    // Seller "My Certified Stock Requests" list
    statusFilter: 'certified-stock-status-filter',
    search: 'certified-stock-search',
    refresh: 'certified-stock-refresh',
    retry: 'certified-stock-retry',
    detailPanel: 'certified-stock-detail-panel',
    openDealRoom: (id: string) => `certified-stock-open-deal-room-${id}`,
    viewRequest: (id: string) => `certified-stock-view-request-${id}`,
    // Seller request detail (Ticket 8.3)
    markShipped: 'certified-stock-mark-shipped',
    back: 'certified-stock-back',
    openFullPage: 'certified-stock-open-full-page',
    openListing: 'certified-stock-open-listing',
    detailRefresh: 'certified-stock-detail-refresh',
    panelRefresh: 'certified-stock-panel-refresh',
    // Dealer read-only linked-inspection view (reached from the request detail)
    openInspection: 'certified-stock-open-inspection',
    inspectionBack: 'certified-stock-inspection-back',
    inspectionRetry: 'certified-stock-inspection-retry',
    inspectionReportDoc: (fileName: string) => `certified-stock-inspection-report-doc-${fileName}`,
  },
  adminCertifiedStock: {
    statusFilter: 'admin-certified-stock-status-filter',
    search: 'admin-certified-stock-search',
    refresh: 'admin-certified-stock-refresh',
    detailRefresh: 'admin-certified-stock-detail-refresh',
    panelRefresh: 'admin-certified-stock-panel-refresh',
    retry: 'admin-certified-stock-retry',
    view: (id: string) => `admin-certified-stock-view-${id}`,
    detailPanel: 'admin-certified-stock-detail-panel',
    openDealRoom: 'admin-certified-stock-open-deal-room',
    openInspection: 'admin-certified-stock-open-inspection',
    openFullPage: 'admin-certified-stock-open-full-page',
    openListing: 'admin-certified-stock-open-listing',
    back: 'admin-certified-stock-back',
    // Approve / reject from the detail view
    approveTrigger: 'admin-certified-stock-approve-trigger',
    approveDialog: 'admin-certified-stock-approve-dialog',
    approveShipping: 'admin-certified-stock-approve-shipping',
    approveSubmit: 'admin-certified-stock-approve-submit',
    approveCancel: 'admin-certified-stock-approve-cancel',
    rejectTrigger: 'admin-certified-stock-reject-trigger',
    rejectReason: 'admin-certified-stock-reject-reason',
    rejectSubmit: 'admin-certified-stock-reject-submit',
    rejectCancel: 'admin-certified-stock-reject-cancel',
    // Mark received (Ticket 8.3)
    receivedTrigger: 'admin-certified-stock-received-trigger',
    // Assign inspector (Ticket 8.4)
    assignInspectorTrigger: 'admin-certified-stock-assign-inspector-trigger',
    partnerSelect: 'admin-certified-stock-partner-select',
    assignSubmit: 'admin-certified-stock-assign-submit',
    assignCancel: 'admin-certified-stock-assign-cancel',
    // Certify/fail decision (Ticket 8.5)
    certifyTrigger: 'admin-certified-stock-certify-trigger',
    failTrigger: 'admin-certified-stock-fail-trigger',
    decideConfirm: 'admin-certified-stock-decide-confirm',
    decideCancel: 'admin-certified-stock-decide-cancel',
  },
  inspection: {
    buyerRequest: 'buyer-request-inspection',
    sellerRequest: 'seller-request-inspection',
    standaloneTrigger: 'seller-standalone-inspection-trigger',
    standaloneNote: 'seller-standalone-inspection-note',
    standaloneSubmit: 'seller-standalone-inspection-submit',
    standaloneCancel: 'seller-standalone-inspection-cancel',
    openDealRoom: 'open-deal-room',
    completeTrigger: 'inspection-complete-trigger',
    completeConfirm: 'inspection-complete-confirm',
    completeCancel: 'inspection-complete-cancel',
    viewInspections: 'inspection-view-inspections',
    viewInspectionsSeller: 'inspection-view-inspections-seller',
  },
  inspectionReport: {
    viewTrigger: 'view-inspection-report-trigger',
    panel: 'view-inspection-report-panel',
    retry: 'view-inspection-report-retry',
    doc: (fileName: string) => `view-inspection-report-doc-${fileName}`,
  },
  dealRooms: {
    list: 'deal-rooms-list',
    retry: 'deal-rooms-retry',
    search: 'deal-rooms-list-search',
    refresh: 'deal-rooms-list-refresh',
    panelRefresh: 'deal-room-panel-refresh',
    detailRefresh: 'deal-room-detail-refresh',
    view: (id: string) => `deal-room-view-${id}`,
    back: 'deal-room-back',
    document: (eventId: string) => `deal-room-document-${eventId}`,
    completeSecurePayment: 'deal-room-complete-secure-payment',
  },
  listingPhotos: {
    input: 'listing-photos-input',
    moveEarlier: (index: number) => `listing-photo-move-earlier-${index}`,
    moveLater: (index: number) => `listing-photo-move-later-${index}`,
    remove: (index: number) => `listing-photo-remove-${index}`,
  },
  listingForm: {
    useCasesTree: 'listing-use-cases-tree',
    useCasesSearch: 'listing-use-cases-search',
    useCasesTreeExpand: (key: string) => `listing-use-cases-tree-expand-${key}`,
    useCasesTreeNode: (key: string) => `listing-use-cases-tree-node-${key}`,
    specBoolean: (key: string) => `spec-boolean-${key}`,
    specFileUpload: (key: string) => `spec-file-upload-${key}`,
  },
  partnerListings: {
    panelRefresh: 'partner-listing-panel-refresh',
    detailRefresh: 'partner-listing-detail-refresh',
    listRefresh: 'partner-listings-refresh',
    confirmAvailable: 'partner-listing-confirm-available',
    view: (id: string) => `partner-listing-view-${id}`,
  },
  listingInventory: {
    manageOpen: 'listing-inventory-manage-open',
    adminViewOpen: 'listing-inventory-admin-view-open',
    sidePanel: 'listing-inventory-side-panel',
    panel: 'listing-inventory-panel',
    inUnitsField: 'listing-inventory-in-units-field',
    inRemarksField: 'listing-inventory-in-remarks-field',
    outUnitsField: 'listing-inventory-out-units-field',
    outRemarksField: 'listing-inventory-out-remarks-field',
    inSubmit: 'listing-inventory-in-submit',
    outSubmit: 'listing-inventory-out-submit',
    inActions: 'listing-inventory-in-actions',
    outActions: 'listing-inventory-out-actions',
    historyTable: 'listing-inventory-history-table',
    historyTimeline: 'listing-inventory-history-timeline',
    historyRefresh: 'listing-inventory-history-refresh',
    historyPagination: 'listing-inventory-history-pagination',
    historyRetry: 'listing-inventory-history-retry',
    notifyWhenAvailable: 'marketplace-notify-when-available',
  },
  listingDetail: {
    specsSection: 'listing-detail-specs-section',
    specRow: (key: string) => `listing-detail-spec-${key}`,
    specFileLink: (key: string) => `listing-detail-spec-file-${key}`,
    sensorsSection: 'listing-detail-sensors-section',
    sensor: (key: string) => `listing-detail-sensor-${key}`,
    useCasesSection: 'listing-detail-use-cases-section',
    useCase: (key: string) => `listing-detail-use-case-${key}`,
    sellerSection: 'listing-detail-seller-section',
    sellerAvatar: 'listing-detail-seller-avatar',
    sellerName: 'listing-detail-seller-name',
    sellerRole: 'listing-detail-seller-role',
    sellerLocation: 'listing-detail-seller-location',
    sellerListed: 'listing-detail-seller-listed',
    sellerEngagement: 'listing-detail-seller-engagement',
  },
  profilePhoto: {
    trigger: 'profile-photo',
    input: 'profile-photo-input',
    replace: 'profile-photo-replace',
    remove: 'profile-photo-remove',
    upload: 'profile-photo-upload',
  },
  /**
   * Notification bell (header), dropdown panel, and full inbox view across all dashboards. The bell
   * is mounted on every dashboard page — including the inbox page — so the dropdown and the inbox use
   * distinct id sets to stay unique when both are in the DOM at once.
   */
  notifications: {
    bell: 'notifications-bell',
    badge: 'notifications-unread-badge',
    viewAll: 'notifications-view-all',
    // Header dropdown panel
    panel: 'notifications-panel',
    panelMarkAll: 'notifications-panel-mark-all',
    panelRefresh: 'notifications-panel-refresh',
    panelList: 'notifications-panel-list',
    panelItem: (id: string) => `notifications-panel-item-${id}`,
    panelEmpty: 'notifications-panel-empty',
    panelSkeleton: 'notifications-panel-skeleton',
    panelRetry: 'notifications-panel-retry',
    // Full inbox view
    markAll: 'notifications-mark-all',
    refresh: 'notifications-refresh',
    clearAll: 'notifications-clear-all',
    clearDialog: 'notifications-clear-dialog',
    clearConfirm: 'notifications-clear-confirm',
    clearCancel: 'notifications-clear-cancel',
    list: 'notifications-list',
    inboxSkeleton: 'notifications-inbox-skeleton',
    item: (id: string) => `notification-item-${id}`,
    itemLink: (id: string) => `notification-item-link-${id}`,
    markRead: (id: string) => `notification-mark-read-${id}`,
    delete: (id: string) => `notification-delete-${id}`,
    empty: 'notifications-empty',
    retry: 'notifications-retry',
    pagination: 'notifications-pagination',
  },
  marketplace: {
    browse: {
      search: 'marketplace-browse-search',
      sort: 'marketplace-browse-sort',
      filterSidebar: 'marketplace-browse-filter-sidebar',
      filterMobileOpen: 'marketplace-browse-filter-mobile-open',
      filterMobilePanel: 'marketplace-browse-filter-mobile-panel',
      filterPriceRangeError: 'marketplace-browse-filter-price-range-error',
      filterPriceMin: 'marketplace-browse-filter-price-min',
      filterPriceMax: 'marketplace-browse-filter-price-max',
      filterCountries: 'marketplace-browse-filter-countries',
      filterUseCases: 'marketplace-browse-filter-use-cases',
      filterUsedConditions: 'marketplace-browse-filter-used-conditions',
      filterCountry: (key: string) => `marketplace-browse-filter-country-${key}`,
      filterUseCase: (key: string) => `marketplace-browse-filter-use-case-${key}`,
      filterUsedCondition: (key: string) => `marketplace-browse-filter-used-condition-${key}`,
      filterCondition: (key: string) => `marketplace-browse-filter-condition-${key}`,
      grid: 'marketplace-browse-grid',
      gridSkeleton: 'marketplace-browse-grid-skeleton',
      empty: 'marketplace-browse-empty',
      clearFilters: 'marketplace-browse-clear-filters',
      pagination: 'marketplace-browse-pagination',
      retry: 'marketplace-browse-retry',
      footer: 'marketplace-browse-footer',
      relatedLinks: 'marketplace-browse-related-links',
      relatedLink: (href: string) => `marketplace-browse-related-link-${href.replace(/[^a-z0-9]+/gi, '-')}`,
      pageContent: 'marketplace-browse-page-content',
      faq: 'marketplace-browse-faq',
      faqItem: (index: number) => `marketplace-browse-faq-item-${index}`,
      card: (id: string) => `marketplace-browse-card-${id}`,
      compare: (id: string) => `marketplace-browse-compare-${id}`,
      useCaseStrip: 'marketplace-browse-use-case-strip',
      useCaseStripViewAll: 'marketplace-browse-use-case-strip-view-all',
      useCaseStripItem: (key: string) => `marketplace-browse-use-case-strip-${key}`,
      brandStrip: 'marketplace-browse-brand-strip',
      brandStripViewAll: 'marketplace-browse-brand-strip-view-all',
      brandStripItem: (key: string) => `marketplace-browse-brand-strip-${key}`,
      manufacturer: 'marketplace-browse-filter-manufacturer',
      model: 'marketplace-browse-filter-model',
    },
    usecase: {
      categoryGrid: 'marketplace-usecase-category-grid',
      categoryItem: (key: string) => `marketplace-usecase-category-${key}`,
      viewAllCategories: 'marketplace-usecase-view-all-categories',
      hubEmpty: 'marketplace-usecase-hub-empty',
    },
    manufacturer: {
      brandGrid: 'marketplace-manufacturer-brand-grid',
      brandItem: (key: string) => `marketplace-manufacturer-brand-${key}`,
      viewAllBrands: 'marketplace-manufacturer-view-all-brands',
      hubEmpty: 'marketplace-manufacturer-hub-empty',
    },
    breadcrumbs: {
      root: 'marketplace-breadcrumbs',
    },
    detail: {
      back: 'marketplace-detail-back',
      gallery: 'marketplace-detail-gallery',
      galleryThumb: (id: string) => `marketplace-detail-gallery-thumb-${id}`,
      sidebar: 'marketplace-detail-sidebar',
      seller: 'marketplace-detail-seller',
      sellerAvatar: 'marketplace-detail-seller-avatar',
      sellerName: 'marketplace-detail-seller-name',
      sellerRole: 'marketplace-detail-seller-role',
      sellerLocation: 'marketplace-detail-seller-location',
      sellerListed: 'marketplace-detail-seller-listed',
      sellerEngagement: 'marketplace-detail-seller-engagement',
      sellerTrustBadge: (index: number) => `marketplace-detail-seller-trust-badge-${index}`,
      trust: 'marketplace-detail-trust',
      logistics: 'marketplace-detail-logistics',
      description: 'marketplace-detail-description',
      retry: 'marketplace-detail-retry',
      action: (key: string) => `marketplace-detail-action-${key}`,
      purchaseBundles: 'marketplace-detail-purchase-bundles',
      purchaseBundle: (bundle: string) => `marketplace-detail-purchase-bundle-${bundle}`,
      purchaseBundleAction: (bundle: string) => `marketplace-detail-purchase-bundle-action-${bundle}`,
      makeItGreenPath: 'marketplace-detail-make-it-green-path',
      matchBlock: 'marketplace-detail-match-block',
      trustTile: (key: string) => `marketplace-detail-trust-${key}`,
    },
    compare: {
      page: 'marketplace-compare-page',
      empty: 'marketplace-compare-empty',
      emptySuggestion: (id: string) => `marketplace-compare-empty-suggestion-${id}`,
      grid: 'marketplace-compare-grid',
      addColumn: 'marketplace-compare-add-column',
      quickAdd: (id: string) => `marketplace-compare-quick-add-${id}`,
      column: (id: string) => `marketplace-compare-column-${id}`,
      remove: (id: string) => `marketplace-compare-remove-${id}`,
      viewDetails: (id: string) => `marketplace-compare-view-details-${id}`,
      row: (key: string) => `marketplace-compare-row-${key}`,
      headerLink: 'marketplace-compare-header-link',
      headerBadge: 'marketplace-compare-header-badge',
      browseListings: 'marketplace-compare-browse-listings',
      retry: 'marketplace-compare-retry',
    },
  },
  publicPages: {
    footer: 'public-pages-footer',
    footerTermsLink: 'public-pages-footer-terms-link',
    footerPrivacyLink: 'public-pages-footer-privacy-link',
    agreementNotice: 'public-pages-agreement-notice',
    agreementTermsLink: 'public-pages-agreement-terms-link',
    agreementPrivacyLink: 'public-pages-agreement-privacy-link',
    page: (pageId: string) => `public-pages-${pageId}`,
    admin: {
      page: 'admin-public-pages-page',
      create: 'admin-public-pages-create',
      createPage: 'admin-public-pages-create-page',
      fieldKey: 'admin-public-pages-field-key',
      refresh: 'admin-public-pages-refresh',
      loading: 'admin-public-pages-loading',
      retry: 'admin-public-pages-retry',
      table: 'admin-public-pages-table',
      row: (key: string) => `admin-public-pages-row-${key}`,
      edit: (key: string) => `admin-public-pages-edit-${key}`,
      editPage: (key: string) => `admin-public-pages-edit-page-${key}`,
      viewPublic: (key: string) => `admin-public-pages-view-public-${key}`,
      backToList: 'admin-public-pages-back-to-list',
      editorLoading: 'admin-public-pages-editor-loading',
      editorRetry: 'admin-public-pages-editor-retry',
      editorActions: 'admin-public-pages-editor-actions',
      cancel: 'admin-public-pages-cancel',
      submit: 'admin-public-pages-submit',
      previewPanel: 'admin-public-pages-preview-panel',
      previewBody: 'admin-public-pages-preview-body',
      previewBodyContainer: 'admin-public-pages-preview-body-container',
      previewToggle: 'admin-public-pages-preview-toggle',
    },
  },
  systemBanners: {
    strip: 'system-banner-strip',
    stripDismiss: 'system-banner-strip-dismiss',
    stripLink: 'system-banner-strip-link',
    modal: 'system-banner-modal',
    admin: {
      page: 'admin-system-banners-page',
      refresh: 'admin-system-banners-refresh',
      create: 'admin-system-banners-create',
      createDialog: 'admin-system-banners-create-dialog',
      edit: (id: string) => `admin-system-banners-edit-${id}`,
      publish: (id: string) => `admin-system-banners-publish-${id}`,
      unpublish: (id: string) => `admin-system-banners-unpublish-${id}`,
    },
  },
  payments: {
    admin: {
      page: 'admin-payments-platform-settings-page',
      refresh: 'admin-payments-platform-settings-refresh',
      retry: 'admin-payments-platform-settings-retry',
      save: 'admin-payments-platform-settings-save',
      providerOption: (provider: string) =>
        `admin-payments-platform-provider-${provider.toLowerCase().replace(/_/g, '-')}`,
      stripePlatformFee: 'admin-payments-platform-stripe-fee',
    },
    securePurchases: {
      page: 'admin-secure-purchases-page',
      refresh: 'admin-secure-purchases-refresh',
      retry: 'admin-secure-purchases-retry',
      tabs: 'admin-secure-purchases-tabs',
      pagination: 'admin-secure-purchases-pagination',
      detailPanel: 'admin-secure-purchases-detail-panel',
      openDealRoom: 'admin-secure-purchases-open-deal-room',
      row: (id: string) => `admin-secure-purchases-row-${id}`,
      view: (id: string) => `admin-secure-purchases-view-${id}`,
      disputesTab: 'admin-secure-purchases-disputes-tab',
    },
    profile: {
      section: 'profile-payment-settings-section',
      stripeConnect: 'profile-payment-stripe-connect',
      stripeGuidance: 'profile-payment-stripe-guidance',
      escrowRegister: 'profile-payment-escrow-register',
      retry: 'profile-payment-settings-retry',
    },
    checkout: {
      dialog: 'buy-via-constellation-dialog',
      confirm: 'buy-via-constellation-confirm',
      cancel: 'buy-via-constellation-cancel',
      open: 'buy-via-constellation-open',
      signIn: 'buy-via-constellation-sign-in',
      stripeCheckout: 'buy-via-constellation-stripe-checkout',
    },
    confirmation: {
      page: 'payment-confirmation-page',
      retry: 'payment-confirmation-retry',
      openDealRoom: 'payment-confirmation-open-deal-room',
      viewListing: 'payment-confirmation-view-listing',
    },
  },
  expertCredits: {
    admin: {
      settingsRefresh: 'admin-expert-credits-settings-refresh',
      settingsSave: 'admin-expert-credits-settings-save',
      settingsRetry: 'admin-expert-credits-settings-retry',
      packageAdd: 'admin-expert-credits-package-add',
      packageEdit: (key: string) => `admin-expert-credits-package-edit-${key}`,
      packageDelete: (key: string) => `admin-expert-credits-package-delete-${key}`,
      packageSubmit: 'admin-expert-credits-package-submit',
      packageWorkCategory: 'admin-expert-credits-package-work-category',
      workCategoryEdit: (key: string) => `admin-expert-credits-work-category-edit-${key}`,
      workCategorySubmit: 'admin-expert-credits-work-category-submit',
      walletSearch: 'admin-expert-credits-wallet-search',
      walletRefresh: 'admin-expert-credits-wallet-refresh',
      walletRetry: 'admin-expert-credits-wallet-retry',
      walletView: (userId: string) => `admin-expert-credits-wallet-view-${userId}`,
      walletPanel: 'admin-expert-credits-wallet-panel',
      walletPanelRefresh: 'admin-expert-credits-wallet-panel-refresh',
      walletAdjust: 'admin-expert-credits-wallet-adjust',
      walletAdjustSubmit: 'admin-expert-credits-wallet-adjust-submit',
      packageRefresh: 'admin-expert-credits-packages-refresh',
      workCategoryRefresh: 'admin-expert-credits-work-categories-refresh',
    },
    buyer: {
      refresh: 'buyer-expert-credits-refresh',
      retry: 'buyer-expert-credits-retry',
      balance: 'buyer-expert-credits-balance',
      lifetimePurchased: 'buyer-expert-credits-lifetime-purchased',
      lifetimeUsed: 'buyer-expert-credits-lifetime-used',
      activePackageCount: 'buyer-expert-credits-active-package-count',
      activePackageRow: (purchaseId: string) => `buyer-expert-credits-active-package-${purchaseId}`,
      historyPagination: 'buyer-expert-credits-history-pagination',
      packageCard: (key: string) => `buyer-expert-credits-package-${key}`,
      packageBuy: (key: string) => `buyer-expert-credits-buy-${key}`,
      checkoutDialog: 'buyer-expert-credits-checkout-dialog',
      checkoutStart: 'buyer-expert-credits-checkout-start',
      confirmationPage: 'buyer-expert-credits-confirmation-page',
      confirmationRetry: 'buyer-expert-credits-confirmation-retry',
    },
  },
  matching: {
    guidedSearch: {
      form: 'matching-guided-search-form',
      submit: 'matching-guided-search-submit',
      improveLink: 'matching-guided-search-improve',
    },
    builder: {
      form: 'matching-builder-form',
      submit: 'matching-builder-submit',
      back: 'matching-builder-back',
    },
    results: {
      page: 'matching-results-page',
      save: 'matching-results-save',
      changeRequirements: 'matching-results-change',
      refresh: 'matching-results-refresh',
      strip: (resultId: string) => `matching-result-strip-${resultId}`,
      viewDetails: (resultId: string) => `matching-result-view-details-${resultId}`,
      purchaseBundle: (resultId: string, bundle: string) => `matching-result-bundle-${resultId}-${bundle}`,
      stripChangeRequirements: (resultId: string) => `matching-result-change-${resultId}`,
      primaryCta: (resultId: string) => `matching-result-primary-${resultId}`,
      secondaryCta: (resultId: string, cta: string) => `matching-result-secondary-${resultId}-${cta}`,
    },
    outcome: {
      page: 'matching-outcome-page',
      continue: 'matching-outcome-continue',
    },
    creditsDialog: {
      dialog: 'matching-credits-dialog',
      close: 'matching-credits-dialog-close',
      continue: 'matching-credits-dialog-continue',
    },
    saved: {
      page: 'buyer-saved-matches-page',
      refresh: 'buyer-saved-matches-refresh',
      card: (id: string) => `buyer-saved-match-${id}`,
      open: (id: string) => `buyer-saved-match-open-${id}`,
      delete: (id: string) => `buyer-saved-match-delete-${id}`,
      deleteConfirm: 'buyer-saved-match-delete-confirm',
      deleteConfirmSubmit: 'buyer-saved-match-delete-confirm-submit',
      deleteConfirmCancel: 'buyer-saved-match-delete-confirm-cancel',
    },
    admin: {
      weightsPage: 'admin-matching-weights-page',
      weightsSave: 'admin-matching-weights-save',
      weightsRefresh: 'admin-matching-weights-refresh',
      thresholdsPage: 'admin-matching-thresholds-page',
      thresholdsSave: 'admin-matching-thresholds-save',
      thresholdsRefresh: 'admin-matching-thresholds-refresh',
      overridesPage: 'admin-matching-overrides-page',
      overridesRefresh: 'admin-matching-overrides-refresh',
      flaggedRow: (resultId: string) => `admin-matching-flagged-${resultId}`,
      review: (resultId: string) => `admin-matching-review-${resultId}`,
      reviewPanel: 'admin-matching-review-panel',
      overrideSubmit: 'admin-matching-override-submit',
    },
  },
  upworkProfile: {
    title: 'upwork-profile-title',
    overview: 'upwork-profile-overview',
    skills: 'upwork-profile-skills',
    hourlyRateMin: 'upwork-profile-rate-min',
    hourlyRateMax: 'upwork-profile-rate-max',
    country: 'upwork-profile-country',
    timezone: 'upwork-profile-timezone',
    languages: 'upwork-profile-languages',
    exclusions: 'upwork-profile-exclusions',
    profileUrl: 'upwork-profile-url',
    label: 'upwork-profile-label',
    save: 'upwork-profile-save',
    pendingDraft: 'upwork-profile-pending-draft',
    confirmImport: 'upwork-profile-confirm-import',
    discardImport: 'upwork-profile-discard-import',
    profileSelect: 'upwork-profile-select',
    createProfile: 'upwork-profile-create',
    deleteProfile: 'upwork-profile-delete',
    backToList: 'upwork-profile-back',
    detailRefresh: 'upwork-profile-detail-refresh',
    retry: 'upwork-profile-retry',
    profileCard: (id: string) => `upwork-profile-card-${id}`,
    draftCard: 'upwork-profile-draft-card',
  },
  upworkFilters: {
    json: 'upwork-filters-json',
    generate: 'upwork-filters-generate',
    save: 'upwork-filters-save',
    profileSelect: 'upwork-filters-profile-select',
  },
  upworkExtension: {
    oneClick: 'upwork-extension-one-click',
    generateCode: 'upwork-extension-generate-code',
    copyCode: 'upwork-extension-copy-code',
    codeDisplay: 'upwork-extension-code-display',
  },
  upworkJobs: {
    profileSelect: 'upwork-jobs-profile-select',
    runNow: 'upwork-jobs-run-now',
    refresh: 'upwork-jobs-refresh',
    search: 'upwork-jobs-search',
    openFilters: 'upwork-jobs-open-filters',
    filtersPanel: 'upwork-jobs-filters-panel',
    minScore: 'upwork-jobs-min-score',
    sort: 'upwork-jobs-sort',
    scrapedFrom: 'upwork-jobs-scraped-from',
    scrapedTo: 'upwork-jobs-scraped-to',
    applyFilters: 'upwork-jobs-apply-filters',
    clearFilters: 'upwork-jobs-clear-filters',
    runStatus: 'upwork-jobs-run-status',
    runList: 'upwork-jobs-run-list',
    runShowNew: (id: string) => `upwork-jobs-run-new-${id}`,
    table: 'upwork-jobs-table',
    pagination: 'upwork-jobs-pagination',
    retry: 'upwork-jobs-retry',
    backToList: 'upwork-jobs-back',
    detail: 'upwork-jobs-detail',
    detailRefresh: 'upwork-jobs-detail-refresh',
    skillMatches: 'upwork-jobs-skill-matches',
    skillMatched: (skill: string) => `upwork-jobs-skill-matched-${skill}`,
    skillMissing: (skill: string) => `upwork-jobs-skill-missing-${skill}`,
    row: (id: string) => `upwork-jobs-row-${id}`,
    openJob: (id: string) => `upwork-jobs-open-${id}`,
    openDetail: (id: string) => `upwork-jobs-detail-link-${id}`,
  },
  upworkScoring: {
    refresh: 'upwork-scoring-refresh',
    save: 'upwork-scoring-save',
    reset: 'upwork-scoring-reset',
    weightSkills: 'upwork-scoring-weight-skills',
    weightKeywords: 'upwork-scoring-weight-keywords',
    weightBudget: 'upwork-scoring-weight-budget',
    weightLocation: 'upwork-scoring-weight-location',
    weightClientRating: 'upwork-scoring-weight-client-rating',
    weightProposals: 'upwork-scoring-weight-proposals',
    thresholdGreen: 'upwork-scoring-threshold-green',
    thresholdOrange: 'upwork-scoring-threshold-orange',
    thresholdYellow: 'upwork-scoring-threshold-yellow',
  },
  upworkDashboard: {
    connectExtension: 'upwork-dashboard-connect-extension',
    syncHint: 'upwork-dashboard-sync-hint',
    profilesSection: 'upwork-dashboard-profiles',
    jobsSection: 'upwork-dashboard-jobs',
    goProfiles: 'upwork-dashboard-go-profiles',
    goJobs: 'upwork-dashboard-go-jobs',
    profileCard: (id: string) => `upwork-dashboard-profile-${id}`,
    jobCard: (id: string) => `upwork-dashboard-job-${id}`,
  },
} as const;
