name: PR checks

on:
  pull_request:
    branches:
      - master
      - staging

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Lint
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Build
        run: pnpm build
